### ISSUE TITLE
How fix this problem?

### ISSUE THREAD

**Issue by 4eJliK** [odin-fan/enatega-backend-api#3]
I highlighted a line that's white in bash when the others are gray.

$ node app.js
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module '../../models/restaurant'
Require stack:
- C:\Users\Artem\enatega-backend-api\models\user.js
- C:\Users\Artem\enatega-backend-api\models\auth.js
- C:\Users\Artem\enatega-backend-api\models\index.js
- C:\Users\Artem\enatega-backend-api\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\Artem\enatega-backend-api\models\user.js:4:2
0)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Artem\\enatega-backend-api\\models\\user.js',
    'C:\\Users\\Artem\\enatega-backend-api\\models\\auth.js',
    'C:\\Users\\Artem\\enatega-backend-api\\models\\index.js',
    'C:\\Users\\Artem\\enatega-backend-api\\app.js'
  ]
}

Node.js v20.18.0

    at Object.<anonymous> (C:\Users\Artem\enatega-backend-api\models\user.js:4:2
0)

**Comment by 4eJliK** [comment]
I found the solution, you need to recheck the file you have in error, and in the file was specified '../../models/restaurant', and since they are in 1 directory, you need to replace '../../models/restaurant' with './restaurant'.
